[phases.setup]
nixPkgs = ["...", "python3", "gcc", "gnumake"]

[phases.install]
cmds = [
  "npm ci --ignore-scripts --no-audit --no-fund",
  "npm rebuild bcrypt esbuild --foreground-scripts",
  "cd node_modules/better-sqlite3 && node ../node-gyp/bin/node-gyp.js rebuild --release",
  "cd node_modules/sqlite3 && node ../node-gyp/bin/node-gyp.js rebuild"
]
